FROM rocker/shiny

LABEL maintainer "josh janzen"

# system libraries of general use
RUN apt-get update && apt-get install -y \
    sudo \
    pandoc \
    pandoc-citeproc \
    libcurl4-gnutls-dev \
    libcairo2-dev \
    libxt-dev \
    libssl-dev \
    libssh2-1-dev \
    libxml2-dev \
    libpq-dev \
    unixodbc-dev \
    libsasl2-dev \
    libudunits2-dev


# basic shiny functionality
RUN R -e "install.packages(c('shiny'), repos='http://cran.us.r-project.org')"

# to install specific versions: 
RUN R -e "install.packages('devtools')"
RUN R -e "require(devtools)"
RUN R -e "devtools::install_version('leaflet', version = '2.0.4.1', repos = 'http://cran.us.r-project.org')"
RUN R -e "devtools::install_version('extrafont', version = '0.17', repos = 'http://cran.us.r-project.org')"
RUN R -e "devtools::install_version('shinyjs', version = '2.0.0', repos = 'http://cran.us.r-project.org')"
RUN R -e "install.packages(c('echarts4r'), repos='https://cloud.r-project.org/')"
RUN R -e "remotes::install_github('JohnCoene/echarts4r.maps')"


# copy the app to the image
RUN mkdir /root/app
#COPY app /root/app
#COPY Rprofile.site /usr/lib/R/etc/

EXPOSE 3838
CMD ["R", "-e", "shiny::runApp('/root/app', host = '0.0.0.0', port = 3838)"]
