FROM rocker/shiny

LABEL maintainer "tester"

# system libraries of general use
RUN apt-get update && apt-get install -y \
    sudo \
    pandoc \
    pandoc-citeproc \
    libcurl4-gnutls-dev \
    libcairo2-dev \
    libxt-dev \
    libssl-dev \
    libssh2-1-dev \
    libxml2-dev \
    libpq-dev \
    unixodbc-dev \
    libsasl2-dev \
    libudunits2-dev


# basic shiny functionality
RUN R -e "install.packages(c('shiny', 'shinydashboard', 'rmarkdown'), repos='http://cran.us.r-project.org')"

# to install specific versions: 
RUN R -e "install.packages('devtools')"
RUN R -e "require(devtools)"

RUN R -e "devtools::install_version('fresh', version = '0.2.0', repos = 'http://cran.us.r-project.org')"
RUN R -e "devtools::install_version('shinydashboardPlus', version = '2.0.0', repos = 'http://cran.us.r-project.org')"
RUN R -e "devtools::install_version('odbc', version = '1.2.2', repos = 'http://cran.us.r-project.org')"
RUN R -e "devtools::install_version('shinyBS', version = '0.61', repos = 'http://cran.us.r-project.org')"
RUN R -e "devtools::install_version('shinyWidgets', version = '0.4.3', repos = 'http://cran.us.r-project.org')"
RUN R -e "devtools::install_version('dashboardthemes', version = '1.1.3', repos = 'http://cran.us.r-project.org')"
RUN R -e "devtools::install_version('leaflet', version = '2.0.4.1', repos = 'http://cran.us.r-project.org')"
RUN R -e "devtools::install_version('htmlwidgets', version = '1.5.3', repos = 'http://cran.us.r-project.org')"
RUN R -e "devtools::install_version('DT', version = '0.18', repos = 'http://cran.us.r-project.org')"
RUN R -e "devtools::install_version('lubridate', version = '1.7.10', repos = 'http://cran.us.r-project.org')"
RUN R -e "devtools::install_version('tidyverse', version = '1.3.1', repos = 'http://cran.us.r-project.org')"
RUN R -e "devtools::install_version('slickR', version = '0.5.0', repos = 'http://cran.us.r-project.org')"
RUN R -e "devtools::install_version('svglite', version = '2.0.0', repos = 'http://cran.us.r-project.org')"
RUN R -e "devtools::install_version('extrafont', version = '0.17', repos = 'http://cran.us.r-project.org')"
RUN R -e "devtools::install_version('shinyjs', version = '2.0.0', repos = 'http://cran.us.r-project.org')"
RUN R -e "devtools::install_version('showtext', version = '0.9-2', repos = 'http://cran.us.r-project.org')"
RUN R -e "devtools::install_version('revealjs', version = '0.9', repos = 'http://cran.us.r-project.org')"

RUN R -e "install.packages(c('echarts4r'), repos='https://cloud.r-project.org/')"
RUN R -e "remotes::install_github('JohnCoene/echarts4r.maps')"
RUN R -e "install.packages(c('shinyglide'), repos='https://cloud.r-project.org/')"
#RUN R -e "install.packages(c('DT', 'lubridate', 'tidyverse', 'slickR', 'svglite', 'extrafont'), repos='https://cloud.r-project.org/')"
#RUN R -e "install.packages(c('shinyjs'), repos='https://cloud.r-project.org/')"

# copy the app to the image
RUN mkdir /root/app
#COPY app /root/app
#COPY Rprofile.site /usr/lib/R/etc/

EXPOSE 3838
CMD ["R", "-e", "shiny::runApp('/root/app', host = '0.0.0.0', port = 3838)"]
